# Generated by Django 5.2.3 on 2025-08-13 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FixItNow_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='worker_images/'),
        ),
    ]
