# Generated by Django 5.2.3 on 2025-08-13 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FixItNow_app', '0003_alter_worker_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worker',
            name='image',
            field=models.CharField(null=True),
        ),
    ]
