# Generated by Django 5.2.3 on 2025-08-13 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FixItNow_app', '0005_booking_booking_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='address',
            field=models.TextField(max_length=255, null=True),
        ),
    ]
